sudo: required
dist: trusty
cache:
- apt
- ccache
language: generic
env:
  global:
  - CATKIN_WS=~/catkin_ws
  - CATKIN_WS_SRC=${CATKIN_WS}/src
  - CI_ROS_DISTRO="indigo"
  - secure: "hq/S+hFDH44PBWcskCANx2Qli+KE8n8b5a5e+IR5T81j6b/NW8WW9Tx02vQjS8KFHcVNHFd9UcCCiKZrsFqs/GbGjBcRknGTGfslesBzZ2B/eXwR1B6dcG4dnN9xLIZw3j8s+i0JoMn1d3Hx/LJgmXVLdgKp0zrLeYDJCkwJ084nAfe3hgizyqL1JMn9xWIyklpR+qi0KVEeu6aV3w18HpDz87NRG42IRiBtLynTPl39y3H+UQNUKtI9gkIb6fuOQY7e5bK9CcJInQl6RDIWK93BPIzPMrDfzpfej93cP/eyvKbBdmzx6hJRI2qrrEXzY7Aj3gB6W26cQU1A9BoWrRD+pbqC6/EcO8/8LKfyXNj4RWiKkrnUAMMZ48LgLQULVLSEP8PB/KoH0EKB2cm98Tu7DimYUznsyVXfkpMMBj0CDG0Nbi3QiS7j0AcN1ngJkIdn8A64pRHKX/waDLdOPGqnezK5UUqhWrqNwoed8emCxsBvGkbUNL/fsnMtdYThzLvW2b6cMHa1O3brhjVpDLbvieFs/0OBMz02lSlVNE0H6ADJJYiPCF1QHi//D+Dqt1B9ZgwMv3ZfD7xTSdxYFAlcLa1YRKeiDdFMXmz3lxl0IPZLk2Ub4/ScbPzXtidsAnffZoiXZBhGCcHywy/hHLcT/mO3a61hiiwgLujkPcY="
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get update -qq
install:
- export PATH=/usr/bin/:$PATH # work-around Travis PYTHONPATH bug, cf. https://github.com/travis-ci/travis-ci/issues/8048
- bash $TRAVIS_BUILD_DIR/.ci/before_install.sh >> /dev/null
- sudo apt-get install -qq g++-4.9
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
- sudo apt-get install -qq -y python-rosdep python-catkin-tools python-catkin-pkg
- sudo rosdep init
- rosdep update
- rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
- sudo apt-get install -qq -y ros-$CI_ROS_DISTRO-rosbash
script:
- source /opt/ros/$CI_ROS_DISTRO/setup.bash
- mkdir -p $CATKIN_WS_SRC
- ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
- cd $CATKIN_WS_SRC
- catkin_init_workspace
- cd ..
- catkin config --init
- catkin build -i
# Run tests
- source /opt/ros/indigo/setup.bash
- source devel/setup.bash
- roscore & # detached core
- rosrun exotica test_initializers
- rosrun task_map test_maps
before_deploy:
- bash $TRAVIS_BUILD_DIR/.ci/after_success.sh
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
#- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- cd $TRAVIS_BUILD_DIR
- export GIT_TAG=latest
- git push https://$GITHUBKEY@github.com/openhumanoids/exotica :refs/tags/$GIT_TAG
- git tag $GIT_TAG -a -m "Updated tag latest from build $TRAVIS_BUILD_NUMBER" -f
- git push --quiet --tags https://$GITHUBKEY@github.com/openhumanoids/exotica $GIT_TAG > /dev/null 2>&1
branches:
  except:
    - /^build-[0-9a-z\-]*/
    - /^latest*/
deploy:
  provider: releases
  api_key:
    secure: Q5HEVWeizz926t9snRXDsh/rZvYq1Cno6fe9vSdDf8H1FRVyjD5HyOAuvlb5Aawdwzi37oGx+oWQvVUkjNAziLke/pBaW6ni1pdvTxiLWXJCAQawxEtnum1leqqOA7U2zz4ufpTxrCw9ss+f2qcKQP3O3B0DjK7EcsjflBsAz5gAGcut6FAv77pzp6KToKSeKrFuheWTHnoL3r+UXT8WO3Lw82sH1rISosP7SBuumLqcT1TIWoYEdnLgnzFcaKkXDTQW9/2VP8drBR57HsbKj6IplgRoOmXjOREgrgRoQ4hhVi1Zoq8ia9CWa7k7w7WUWqpoHq0MwzMab07nWZBcTw6vGki2d5tGmykHTU+TM8rVRZzOS7uUjnJNUM+5yoWt6IE2PCI6jdJpRH2ZU50BwGVx7etYl8sgQQDL1gdZKBjEWX8cdOCj4aPiCxuuoiTTggI1wvG3UmSUUUA3XIk5hAQ1B5e5fsKcpAluouOWulCYoyS+agK/sZVHyMwiaDSp2ddaRuZmtaJMRWtmOU5IUP89EiJWCqSj9ZY89gp1TPD6+1hmlXOr25K7N83ez3/8aGLHSV7my5gr5fCTpLCe9/3HO7Y+L/7xw0JHtsdxdJ/S4XSK5as+TQEY9QiDNlG0xEsv/g6o7CU3ns0qfM3y+BuoqSY2unyhlRsyL9YjPm4=
  skip_cleanup: true
  file: "exotica.deb"
  on:
    repo: openhumanoids/exotica
    tags: false
    branch: master
